### ISSUE TITLE
feature: Allow creation of SxGeo from Stream 

### ISSUE THREAD

**Issue by s-tarasov** [Detrav/Detrav.SypexGeo.Net#2]
My app don't have direct access to file system. So, it'd be good to use Stream directly.

Example
``` csharp
public class SxGeo 
{
    public SxGeo(Stream stream)
}

using Stream dbStream = _binaryDb.OpenRead(); 
var sxGeo = new SxGeo(dbStream); 
```

I can create Pull request if you don't mind.

**Comment by Detrav** [comment]
Yes, create a Pull Request, I'll take a review, accept and post an update to nuget
